# Generated by Django 5.2.4 on 2025-08-12 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Nome do Item')),
                ('description', models.TextField(default='', verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('average_prep_time', models.DurationField(default=datetime.timedelta(seconds=1200), help_text='Tempo estimado que o prato leva para ficar pronto.', verbose_name='Tempo Médio de Preparo')),
                ('serving_size', models.PositiveSmallIntegerField(default=1, help_text='Quantidade de pessoas que o prato serve.', verbose_name='Serve (pessoas)')),
            ],
            options={
                'verbose_name': 'Item do Cardápio',
                'verbose_name_plural': 'Itens do Cardápio',
                'ordering': ['name'],
            },
        ),
    ]
