# Generated by Django 5.2.4 on 2025-09-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Nome do Item')),
            ],
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
